# Generated by Django 5.1 on 2024-08-27 13:46

import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(db_column='ID_Veiculo', primary_key=True, serialize=False, verbose_name='ID do Veículo')),
                ('placa', models.CharField(db_column='Placa', max_length=10, verbose_name='Placa do Veículo')),
                ('modelo', models.CharField(db_column='Modelo', max_length=100, verbose_name='Modelo do Veículo')),
                ('marca', models.CharField(db_column='Marca', max_length=100, verbose_name='Marca do Veículo')),
                ('ano_fabricacao', models.IntegerField(db_column='Ano_Fabricacao', verbose_name='Ano de Fabricação')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'veiculo',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.AlterField(
            model_name='motorista',
            name='id',
            field=models.AutoField(db_column='ID_Motorista', primary_key=True, serialize=False, verbose_name='ID do Motorista'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_column='tx_email', max_length=256, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.AutoField(db_column='ID_Rota', primary_key=True, serialize=False, verbose_name='ID da Rota')),
                ('data_rota', models.DateField(db_column='Data_Rota', verbose_name='Data da Rota')),
                ('hora_saida', models.TimeField(db_column='Hora_Saida', verbose_name='Horário de Saída')),
                ('hora_chegada', models.TimeField(db_column='Hora_Chegada', verbose_name='Horário de Chegada')),
                ('quantidade_funcionarios', models.IntegerField(db_column='Quantidade_Funcionarios', verbose_name='Quantidade de Funcionários')),
                ('turno', models.CharField(db_column='Turno', max_length=50, verbose_name='Turno')),
                ('fabrica', models.ForeignKey(db_column='ID_Fabrica', on_delete=django.db.models.deletion.PROTECT, to='core.fabrica', verbose_name='Fábrica')),
                ('motorista', models.ForeignKey(db_column='ID_Motorista', on_delete=django.db.models.deletion.PROTECT, to='core.motorista', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'db_table': 'rota',
                'ordering': ['data_rota', 'hora_saida'],
            },
        ),
        migrations.CreateModel(
            name='RotaVeiculo',
            fields=[
                ('id', models.AutoField(db_column='ID_Rota_Veiculo', primary_key=True, serialize=False, verbose_name='ID da Relação Rota-Veículo')),
                ('rota', models.ForeignKey(db_column='ID_Rota', on_delete=django.db.models.deletion.PROTECT, to='core.rota', verbose_name='Rota')),
                ('veiculo', models.ForeignKey(db_column='ID_Veiculo', on_delete=django.db.models.deletion.PROTECT, to='core.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Rota Veículo',
                'verbose_name_plural': 'Rotas Veículos',
                'db_table': 'rota_veiculo',
                'ordering': ['rota', 'veiculo'],
            },
        ),
    ]
