# Generated by Django 5.1 on 2024-08-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_rotaveiculo_rota_remove_rotaveiculo_veiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabrica',
            name='data',
            field=models.DateField(db_column='Data', verbose_name='Data'),
        ),
    ]
